distance_tolerance: 0.005 # m, default: 0.01
angle_tolerance: 0.05 # rad, default: 0.01
linear_velocity: 0.1 # m/s, default: 0.5
angular_velocity: 12.56 # rad/s, default: 12.56 
loop_frequency: 20 # Hz, default: 20
cell_size: 0.18 # m, default 0.18
row_init_position: 0
column_init_position: 0

# PID settings for class control_toobox::PID used in control loop of the Doogie Mouse wheels 
pid:
  linear:
    p: 0.8
    i: 0.0
    d: 0.0
    i_clamp_min: -0.1
    i_clamp_max: 0.1
    antiwindup: true
    publish_state: true

  angular:
    p: 0.1
    i: 0.0
    d: 0.0
    i_clamp_min: -0.0
    i_clamp_max: 0.0
    antiwindup: true
    publish_state: true